{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCallEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallEndReason","preciseIdentifier":"c:@E@TUICallEndReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallObserverExtraInfo","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/oncallend(callid:mediatype:reason:userid:totaltime:info:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/callliststoreimpl\/oncallend(callid:mediatype:reason:userid:totaltime:info:)"]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"TUICallObserver.onCallEnd(callId:mediaType:reason:userId:totalTime:info:)"},{"text":".","type":"text"}],"sections":[],"metadata":{"roleHeading":"Instance Method","title":"onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","symbolKind":"method","navigatorTitle":[{"text":"onCallEnd:mediaType:reason:userId:totalTime:info:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onCallEnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"text":": ","kind":"text"},{"text":"TUICallEndReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@TUICallEndReason"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"totalTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallObserverExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"text":")","kind":"text"}],"modules":[{"name":"AtomicXCore"}],"role":"symbol","extendedModule":"AtomicXCore","externalID":"c:@CM@AtomicXCore@objc(cs)CallListStoreImpl(im)onCallEnd:mediaType:reason:userId:totalTime:info:"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)":{"kind":"symbol","url":"\/documentation\/atomicxcore\/callliststoreimpl\/oncallend(callid:mediatype:reason:userid:totaltime:info:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCallEnd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mediaType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallEndReason","preciseIdentifier":"c:@E@TUICallEndReason","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"totalTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUICallObserverExtraInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"onCallEnd:mediaType:reason:userId:totalTime:info:","kind":"identifier"}],"title":"onCallEnd(callId:mediaType:reason:userId:totalTime:info:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl\/onCallEnd(callId:mediaType:reason:userId:totalTime:info:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallListStoreImpl":{"abstract":[],"url":"\/documentation\/atomicxcore\/callliststoreimpl","kind":"symbol","title":"CallListStoreImpl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallListStoreImpl","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"CallListStoreImpl","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallListStoreImpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onCallEnd:mediaType:reason:userId:totalTime:info:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onCallEnd:mediaType:reason:userId:totalTime:info:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onCallEnd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callId"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TUICallMediaType","preciseIdentifier":"c:@E@TUICallMediaType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mediaType"},{"text":" ","kind":"text"},{"text":"reason:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TUICallEndReason","preciseIdentifier":"c:@E@TUICallEndReason","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"userId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"totalTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"totalTime"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TUICallObserverExtraInfo","preciseIdentifier":"c:objc(cs)TUICallObserverExtraInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallEnd(callId:mediaType:reason:userId:totalTime:info:)\/title","value":"onCallEnd:mediaType:reason:userId:totalTime:info:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl~1onCallEnd(callId:mediaType:reason:userId:totalTime:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCallEnd:mediaType:reason:userId:totalTime:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/title","value":"CallListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/fragments","value":[{"kind":"identifier","text":"CallListStoreImpl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallListStoreImpl\/navigatorTitle","value":[{"kind":"identifier","text":"CallListStoreImpl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}