{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/didMoveToWindow()"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/participantview\/didmovetowindow()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/participantview\/didmovetowindow()"]}],"kind":"symbol","sections":[],"metadata":{"title":"didMoveToWindow()","externalID":"c:@CM@AtomicXCore@objc(cs)ParticipantView(im)didMoveToWindow","modules":[{"name":"AtomicXCore"}],"extendedModule":"AtomicXCore","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView","title":"ParticipantView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantView"}],"navigatorTitle":[{"kind":"identifier","text":"ParticipantView"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/participantview"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView/didMoveToWindow()":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/didMoveToWindow()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":"()","kind":"text"}],"title":"didMoveToWindow()","url":"\/documentation\/atomicxcore\/participantview\/didmovetowindow()","type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"didMoveToWindow","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"didMoveToWindow","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMoveToWindow"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ParticipantView","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ParticipantView"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/navigatorTitle","value":[{"text":"ParticipantView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView~1didMoveToWindow()\/title","value":"didMoveToWindow","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView~1didMoveToWindow()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didMoveToWindow","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}