{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/livecoreview\/unregisterbattleobserver(observer:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/unregisterBattleObserver(observer:)"},"kind":"symbol","metadata":{"platforms":[{"unavailable":false,"beta":false,"deprecated":true}],"roleHeading":"Instance Method","title":"unregisterBattleObserver(observer:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterBattleObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BattleObserver","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)BattleObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"AtomicXCore"}],"role":"symbol","extendedModule":"AtomicXCore","externalID":"s:11AtomicXCore12LiveCoreViewC24unregisterBattleObserver8observeryAA0gH0_p_tF"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterBattleObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","text":"BattleObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)BattleObserver"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","title":"LiveCoreView","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveCoreView","kind":"identifier"}],"navigatorTitle":[{"text":"LiveCoreView","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/unregisterBattleObserver(observer:)":{"kind":"symbol","abstract":[],"type":"topic","title":"unregisterBattleObserver(observer:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/unregisterBattleObserver(observer:)","deprecated":true,"url":"\/documentation\/atomicxcore\/livecoreview\/unregisterbattleobserver(observer:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterBattleObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BattleObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)BattleObserver"},{"text":")","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","title":"BattleObserver","deprecated":true,"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BattleObserver","kind":"identifier"}],"navigatorTitle":[{"text":"BattleObserver","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/battleobserver","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"LiveCoreView","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments","value":[{"text":"LiveCoreView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"LiveCoreView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle"},{"op":"replace","value":"BattleObserver","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/fragments","value":[{"text":"BattleObserver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/navigatorTitle","value":[{"text":"BattleObserver","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}