{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onUserExitBattle(battleId:battleUser:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/atomicxcore\/battleobserver\/onuserexitbattle(battleid:battleuser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/battleobserver\/onuserexitbattle(battleid:battleuser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUserExitBattle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"battleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"battleUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"kind":"text","text":")"}],"externalID":"c:@M@AtomicXCore@objc(pl)BattleObserver(im)onUserExitBattleWithBattleId:battleUser:","platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"modules":[{"name":"AtomicXCore"}],"title":"onUserExitBattle(battleId:battleUser:)","required":true,"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"onUserExitBattleWithBattleId:battleUser:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserExitBattle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"battleId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"battleUser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","title":"BattleObserver","deprecated":true,"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BattleObserver","kind":"identifier"}],"navigatorTitle":[{"text":"BattleObserver","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/battleobserver","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver/onUserExitBattle(battleId:battleUser:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver\/onUserExitBattle(battleId:battleUser:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserExitBattle","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"battleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"battleUser","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser","text":"TUIBattleUser"},{"kind":"text","text":")"}],"deprecated":true,"title":"onUserExitBattle(battleId:battleUser:)","url":"\/documentation\/atomicxcore\/battleobserver\/onuserexitbattle(battleid:battleuser:)","type":"topic","required":true,"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onUserExitBattleWithBattleId:battleUser:"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onUserExitBattleWithBattleId:battleUser:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserExitBattleWithBattleId:battleUser:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onUserExitBattleWithBattleId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"battleId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"battleUser:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TUIBattleUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIBattleUser"},{"text":" *) ","kind":"text"},{"text":"battleUser","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"BattleObserver","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/fragments","value":[{"text":"BattleObserver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/navigatorTitle","value":[{"text":"BattleObserver","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onUserExitBattle(battleId:battleUser:)\/title","value":"onUserExitBattleWithBattleId:battleUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver~1onUserExitBattle(battleId:battleUser:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onUserExitBattleWithBattleId:battleUser:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}