{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onBlackListAdded(infoList:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"V2TIMFriendshipListener.onBlackListAdded(infoList:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBlackListAdded"},{"kind":"text","text":"("},{"text":"infoList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMFriendInfo","preciseIdentifier":"c:objc(cs)V2TIMFriendInfo","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onBlackListAdded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"infoList"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)V2TIMFriendInfo","text":"V2TIMFriendInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"extendedModule":"AtomicXCore","externalID":"c:@CM@AtomicXCore@objc(cs)ContactListStoreImpl(im)onBlackListAdded:","modules":[{"name":"AtomicXCore"}],"title":"onBlackListAdded(infoList:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"onBlackListAdded:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onblacklistadded(infolist:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onblacklistadded(infolist:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl","title":"ContactListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onBlackListAdded(infoList:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onBlackListAdded(infoList:)","title":"onBlackListAdded(infoList:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBlackListAdded","kind":"identifier"},{"kind":"text","text":"("},{"text":"infoList","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)V2TIMFriendInfo","text":"V2TIMFriendInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"onBlackListAdded:","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onblacklistadded(infolist:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onBlackListAdded:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBlackListAdded:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onBlackListAdded:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<V2TIMFriendInfo *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"infoList","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/title","value":"ContactListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/fragments","value":[{"kind":"identifier","text":"ContactListStoreImpl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/navigatorTitle","value":[{"kind":"identifier","text":"ContactListStoreImpl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onBlackListAdded(infoList:)\/title","value":"onBlackListAdded:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onBlackListAdded(infoList:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onBlackListAdded:"}]}]}]}