{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListDeleted(userIDList:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onFriendApplicationListDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIDList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendapplicationlistdeleted(useridlist:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendapplicationlistdeleted(useridlist:)"]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"V2TIMFriendshipListener.onFriendApplicationListDeleted(userIDList:)"},{"type":"text","text":"."}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFriendApplicationListDeleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIDList"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"extendedModule":"AtomicXCore","externalID":"c:@CM@AtomicXCore@objc(cs)ContactListStoreImpl(im)onFriendApplicationListDeleted:","title":"onFriendApplicationListDeleted(userIDList:)","modules":[{"name":"AtomicXCore"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onFriendApplicationListDeleted:"}]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl","title":"ContactListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onFriendApplicationListDeleted(userIDList:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListDeleted(userIDList:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFriendApplicationListDeleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIDList"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"title":"onFriendApplicationListDeleted(userIDList:)","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendapplicationlistdeleted(useridlist:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onFriendApplicationListDeleted:"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onFriendApplicationListDeleted:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onFriendApplicationListDeleted:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onFriendApplicationListDeleted:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"userIDList","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ContactListStoreImpl","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/title"},{"value":[{"text":"ContactListStoreImpl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/fragments"},{"value":[{"text":"ContactListStoreImpl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/navigatorTitle"},{"value":"onFriendApplicationListDeleted:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListDeleted(userIDList:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onFriendApplicationListDeleted:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListDeleted(userIDList:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}