{"variants":[{"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendlistdeleted(useridlist:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendlistdeleted(useridlist:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListDeleted(userIDList:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"method","externalID":"c:@CM@AtomicXCore@objc(cs)ContactListStoreImpl(im)onFriendListDeleted:","modules":[{"name":"AtomicXCore"}],"roleHeading":"Instance Method","title":"onFriendListDeleted(userIDList:)","role":"symbol","extendedModule":"AtomicXCore","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onFriendListDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIDList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"navigatorTitle":[{"text":"onFriendListDeleted:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onFriendListDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIDList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"V2TIMFriendshipListener.onFriendListDeleted(userIDList:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl","title":"ContactListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onFriendListDeleted(userIDList:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListDeleted(userIDList:)","title":"onFriendListDeleted(userIDList:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onFriendListDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIDList","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"navigatorTitle":[{"text":"onFriendListDeleted:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendlistdeleted(useridlist:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onFriendListDeleted:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onFriendListDeleted:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onFriendListDeleted:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"userIDList","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ContactListStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/title","op":"replace"},{"value":[{"text":"ContactListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/fragments","op":"replace"},{"value":[{"text":"ContactListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/navigatorTitle","op":"replace"},{"value":"onFriendListDeleted:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendListDeleted(userIDList:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onFriendListDeleted:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendListDeleted(userIDList:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}