{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl"]]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"V2TIMConversationListener.onConversationChanged(conversationList:)"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationChanged(conversationList:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/onconversationchanged(conversationlist:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/onconversationchanged(conversationlist:)"]}],"metadata":{"roleHeading":"Instance Method","title":"onConversationChanged(conversationList:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onConversationChanged:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMConversation","text":"V2TIMConversation"},{"kind":"text","text":"])"}],"modules":[{"name":"AtomicXCore"}],"role":"symbol","extendedModule":"AtomicXCore","externalID":"c:@CM@AtomicXCore@objc(cs)ConversationListStoreImpl(im)onConversationChanged:"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConversationChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMConversation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMConversation"},{"text":"])","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl","title":"ConversationListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onConversationChanged(conversationList:)":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationChanged(conversationList:)","title":"onConversationChanged(conversationList:)","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/onconversationchanged(conversationlist:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMConversation","text":"V2TIMConversation"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"onConversationChanged:"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onConversationChanged:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConversationChanged:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onConversationChanged:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<V2TIMConversation *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"conversationList","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/title","value":"ConversationListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/fragments","value":[{"text":"ConversationListStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/navigatorTitle","value":[{"text":"ConversationListStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onConversationChanged(conversationList:)\/title","value":"onConversationChanged:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onConversationChanged(conversationList:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConversationChanged:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}