{"metadata":{"title":"onGroupDismissed(groupID:opUser:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onGroupDismissed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"opUser","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)V2TIMGroupMemberInfo","text":"V2TIMGroupMemberInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"AtomicXCore"}],"navigatorTitle":[{"text":"onGroupDismissed:opUser:","kind":"identifier"}],"externalID":"c:@CM@AtomicXCore@objc(cs)ConversationListStoreImpl(im)onGroupDismissed:opUser:","roleHeading":"Instance Method","extendedModule":"AtomicXCore"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/ongroupdismissed(groupid:opuser:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/ongroupdismissed(groupid:opuser:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupDismissed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"opUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"V2TIMGroupMemberInfo","preciseIdentifier":"c:objc(cs)V2TIMGroupMemberInfo"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"V2TIMGroupListener.onGroupDismissed(groupID:opUser:)"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onGroupDismissed(groupID:opUser:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onGroupDismissed(groupID:opUser:)":{"url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/ongroupdismissed(groupid:opuser:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onGroupDismissed(groupID:opUser:)","kind":"symbol","type":"topic","title":"onGroupDismissed(groupID:opUser:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupDismissed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"opUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"V2TIMGroupMemberInfo","preciseIdentifier":"c:objc(cs)V2TIMGroupMemberInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onGroupDismissed:opUser:"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl","title":"ConversationListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onGroupDismissed:opUser:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGroupDismissed:opUser:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onGroupDismissed:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"groupID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"opUser:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"V2TIMGroupMemberInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMGroupMemberInfo"},{"text":" *) ","kind":"text"},{"text":"opUser","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"onGroupDismissed:opUser:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onGroupDismissed(groupID:opUser:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGroupDismissed:opUser:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onGroupDismissed(groupID:opUser:)\/fragments"},{"op":"replace","value":"ConversationListStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ConversationListStoreImpl"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ConversationListStoreImpl"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}