{"variants":[{"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/v2timgrouplistener-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/v2timgrouplistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMGroupListener-Implementations"},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl"]]},"metadata":{"title":"V2TIMGroupListener Implementations","modules":[{"name":"AtomicXCore"}],"roleHeading":"API Collection","role":"collectionGroup"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onGroupDismissed(groupID:opUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onQuitFromGroup(groupID:)"]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onQuitFromGroup(groupID:)":{"url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/onquitfromgroup(groupid:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onQuitFromGroup(groupID:)","kind":"symbol","type":"topic","title":"onQuitFromGroup(groupID:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onQuitFromGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"onQuitFromGroup:"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl","title":"ConversationListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onGroupDismissed(groupID:opUser:)":{"url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/ongroupdismissed(groupid:opuser:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onGroupDismissed(groupID:opUser:)","kind":"symbol","type":"topic","title":"onGroupDismissed(groupID:opUser:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupDismissed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"opUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"V2TIMGroupMemberInfo","preciseIdentifier":"c:objc(cs)V2TIMGroupMemberInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onGroupDismissed:opUser:"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onGroupDismissed(groupID:opUser:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onQuitFromGroup(groupID:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"onQuitFromGroup:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onQuitFromGroup(groupID:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onQuitFromGroup:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onQuitFromGroup(groupID:)\/fragments"},{"value":"ConversationListStoreImpl","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/title"},{"value":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/fragments"},{"value":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/navigatorTitle"},{"value":"onGroupDismissed:opUser:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onGroupDismissed(groupID:opUser:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onGroupDismissed:opUser:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onGroupDismissed(groupID:opUser:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}