{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl"]]},"kind":"article","sections":[],"topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onFriendListDeleted(userIDList:)"],"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMFriendshipListener-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/v2timfriendshiplistener-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/v2timfriendshiplistener-implementations"]}],"metadata":{"modules":[{"name":"AtomicXCore"}],"role":"collectionGroup","roleHeading":"API Collection","title":"V2TIMFriendshipListener Implementations"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onFriendListDeleted(userIDList:)":{"kind":"symbol","abstract":[],"type":"topic","title":"onFriendListDeleted(userIDList:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onFriendListDeleted(userIDList:)","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/onfriendlistdeleted(useridlist:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onFriendListDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIDList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"navigatorTitle":[{"text":"onFriendListDeleted:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl","title":"ConversationListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onFriendListDeleted(userIDList:)"],"title":"Instance Methods"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onFriendListDeleted(userIDList:)\/title","value":"onFriendListDeleted:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onFriendListDeleted(userIDList:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onFriendListDeleted:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/title","value":"ConversationListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/fragments","value":[{"text":"ConversationListStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/navigatorTitle","value":[{"text":"ConversationListStoreImpl","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}