{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gridLayout","kind":"identifier"}],"externalID":"c:@M@AtomicXCore@E@LayoutMode@LayoutModeGridLayout","platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"modules":[{"name":"AtomicXCore"}],"title":"LayoutMode.gridLayout","role":"symbol","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"LayoutModeGridLayout","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/layoutmode\/gridlayout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/layoutmode\/gridlayout"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gridLayout","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/gridLayout"},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode/gridLayout":{"kind":"symbol","url":"\/documentation\/atomicxcore\/layoutmode\/gridlayout","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gridLayout","kind":"identifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"LayoutModeGridLayout","kind":"identifier"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode\/gridLayout","title":"LayoutMode.gridLayout"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LayoutMode":{"abstract":[],"url":"\/documentation\/atomicxcore\/layoutmode","kind":"symbol","title":"LayoutMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LayoutMode","kind":"identifier"}],"deprecated":true,"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LayoutMode"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LayoutMode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"LayoutModeGridLayout","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"LayoutModeGridLayout","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"LayoutModeGridLayout","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/deprecationSummary","value":[],"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1gridLayout\/title","value":"LayoutModeGridLayout","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode~1gridLayout\/fragments","value":[{"text":"LayoutModeGridLayout","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/title","value":"LayoutMode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/fragments","value":[{"text":"LayoutMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LayoutMode\/navigatorTitle","value":[{"text":"LayoutMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}