{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/downloadMessageResource(_:resourceType:completion:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadMessageResource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MessageInfo","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageInfo","preciseIdentifier":"s:11AtomicXCore11MessageInfoV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"resourceType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageMediaFileType","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageMediaFileType","preciseIdentifier":"s:11AtomicXCore20MessageMediaFileTypeO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]}],"metadata":{"title":"downloadMessageResource(_:resourceType:completion:)","externalID":"s:11AtomicXCore20MessageListStoreImplC08downloadC8Resource_12resourceType10completionyAA0C4InfoV_AA0c9MediaFileJ0Oys6ResultOyytAA05ErrorL0VGcSgtF","modules":[{"name":"AtomicXCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadMessageResource","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore11MessageInfoV","text":"MessageInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"resourceType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore20MessageMediaFileTypeO","text":"MessageMediaFileType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/downloadmessageresource(_:resourcetype:completion:)"]}],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageMediaFileType":{"abstract":[],"url":"\/documentation\/atomicxcore\/messagemediafiletype","kind":"symbol","title":"MessageMediaFileType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageMediaFileType"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageMediaFileType"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageMediaFileType"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"abstract":[],"url":"\/documentation\/atomicxcore\/completionclosure","kind":"symbol","title":"CompletionClosure","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/downloadMessageResource(_:resourceType:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/downloadMessageResource(_:resourceType:completion:)","title":"downloadMessageResource(_:resourceType:completion:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadMessageResource","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore11MessageInfoV","kind":"typeIdentifier","text":"MessageInfo"},{"text":", ","kind":"text"},{"text":"resourceType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageMediaFileType","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore20MessageMediaFileTypeO"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/downloadmessageresource(_:resourcetype:completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl","title":"MessageListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStoreImpl"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageInfo":{"abstract":[],"url":"\/documentation\/atomicxcore\/messageinfo","kind":"symbol","title":"MessageInfo","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageInfo","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageInfo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageInfo"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/title","op":"replace","value":"MessageListStoreImpl"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/fragments","op":"replace","value":[{"text":"MessageListStoreImpl","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageListStoreImpl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}