{"metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRecvMessageModified"},{"kind":"text","text":"("},{"kind":"externalParam","text":"msg"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)V2TIMMessage","kind":"typeIdentifier","text":"V2TIMMessage"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"AtomicXCore"}],"navigatorTitle":[{"kind":"identifier","text":"onRecvMessageModified:"}],"title":"onRecvMessageModified(msg:)","externalID":"c:@CM@AtomicXCore@objc(cs)MessageListStoreImpl(im)onRecvMessageModified:","extendedModule":"AtomicXCore"},"variants":[{"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagemodified(msg:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagemodified(msg:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageModified","kind":"identifier"},{"text":"(","kind":"text"},{"text":"msg","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"V2TIMMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMMessage"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"V2TIMAdvancedMsgListener.onRecvMessageModified(msg:)"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageModified(msg:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl","title":"MessageListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStoreImpl"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageModified(msg:)":{"kind":"symbol","abstract":[],"type":"topic","title":"onRecvMessageModified(msg:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageModified(msg:)","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagemodified(msg:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageModified","kind":"identifier"},{"text":"(","kind":"text"},{"text":"msg","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)V2TIMMessage","text":"V2TIMMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onRecvMessageModified:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onRecvMessageModified:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageModified:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onRecvMessageModified:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMMessage","text":"V2TIMMessage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"msg"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/title","value":"MessageListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/fragments","value":[{"text":"MessageListStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/navigatorTitle","value":[{"text":"MessageListStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageModified(msg:)\/title","value":"onRecvMessageModified:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageModified(msg:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageModified:","kind":"identifier"}]}]}]}