{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/state"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisher","text":"StatePublisher","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore14StatePublisherC"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListState","text":"MessageListState","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore16MessageListStateV"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"state","externalID":"s:11AtomicXCore16MessageListStoreC5stateAA14StatePublisherCyAA0cdG0VGvp","modules":[{"name":"AtomicXCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatePublisher","preciseIdentifier":"s:11AtomicXCore14StatePublisherC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MessageListState","preciseIdentifier":"s:11AtomicXCore16MessageListStateV","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/messageliststore\/state"]}],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore","title":"MessageListStore","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStore","kind":"identifier"}],"navigatorTitle":[{"text":"MessageListStore","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListState":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListState","title":"MessageListState","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListState","kind":"identifier"}],"navigatorTitle":[{"text":"MessageListState","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststate"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore/state":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore\/state","title":"state","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatePublisher","preciseIdentifier":"s:11AtomicXCore14StatePublisherC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"MessageListState","preciseIdentifier":"s:11AtomicXCore16MessageListStateV","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststore\/state"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/StatePublisher":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisher","title":"StatePublisher","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatePublisher","kind":"identifier"}],"navigatorTitle":[{"text":"StatePublisher","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/statepublisher"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"value":"MessageListStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/title","op":"replace"},{"value":[{"text":"MessageListStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/fragments","op":"replace"},{"value":[{"text":"MessageListStore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}