{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionCancelled(hostUser:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectioncancelled(hostuser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectioncancelled(hostuser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","platforms":[{"deprecated":true,"unavailable":false,"beta":false}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCrossRoomConnectionCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hostUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIConnectionUser","preciseIdentifier":"c:objc(cs)TUIConnectionUser","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"AtomicXCore"}],"required":true,"navigatorTitle":[{"text":"onCrossRoomConnectionCancelledWithHostUser:","kind":"identifier"}],"roleHeading":"Instance Method","title":"onCrossRoomConnectionCancelled(hostUser:)","externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onCrossRoomConnectionCancelledWithHostUser:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCrossRoomConnectionCancelled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"hostUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser","text":"TUIConnectionUser"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onCrossRoomConnectionCancelled(hostUser:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onCrossRoomConnectionCancelled(hostUser:)","title":"onCrossRoomConnectionCancelled(hostUser:)","required":true,"deprecated":true,"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onCrossRoomConnectionCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"hostUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIConnectionUser","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onCrossRoomConnectionCancelledWithHostUser:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/connectionobserver\/oncrossroomconnectioncancelled(hostuser:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"url":"\/documentation\/atomicxcore\/connectionobserver","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","kind":"symbol","deprecated":true,"type":"topic","title":"ConnectionObserver","role":"symbol","abstract":[{"text":"************************************** observer ***************************************","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionObserver"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":[{"unavailable":false,"deprecated":true,"beta":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onCrossRoomConnectionCancelledWithHostUser:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onCrossRoomConnectionCancelledWithHostUser:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onCrossRoomConnectionCancelledWithHostUser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TUIConnectionUser","preciseIdentifier":"c:objc(cs)TUIConnectionUser"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"hostUser"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionCancelled(hostUser:)\/title","value":"onCrossRoomConnectionCancelledWithHostUser:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onCrossRoomConnectionCancelled(hostUser:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onCrossRoomConnectionCancelledWithHostUser:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title","value":"ConnectionObserver","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments","value":[{"text":"ConnectionObserver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle","value":[{"text":"ConnectionObserver","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}