{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionrequest(inviteruser:)"]},{"paths":["\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionrequest(inviteruser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRequest(inviterUser:)"},"kind":"symbol","metadata":{"platforms":[{"beta":false,"unavailable":false,"deprecated":true}],"title":"onUserConnectionRequest(inviterUser:)","required":true,"externalID":"c:@M@AtomicXCore@objc(pl)ConnectionObserver(im)onUserConnectionRequestWithInviterUser:","modules":[{"name":"AtomicXCore"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserConnectionRequest"},{"kind":"text","text":"("},{"text":"inviterUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onUserConnectionRequestWithInviterUser:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserConnectionRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inviterUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver/onUserConnectionRequest(inviterUser:)":{"abstract":[],"url":"\/documentation\/atomicxcore\/connectionobserver\/onuserconnectionrequest(inviteruser:)","kind":"symbol","title":"onUserConnectionRequest(inviterUser:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onUserConnectionRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"inviterUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TUIUserInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)TUIUserInfo"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"onUserConnectionRequestWithInviterUser:"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver\/onUserConnectionRequest(inviterUser:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConnectionObserver":{"url":"\/documentation\/atomicxcore\/connectionobserver","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConnectionObserver","kind":"symbol","deprecated":true,"type":"topic","title":"ConnectionObserver","role":"symbol","abstract":[{"text":"************************************** observer ***************************************","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionObserver"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionObserver"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"beta":false,"deprecated":true}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onUserConnectionRequestWithInviterUser:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onUserConnectionRequestWithInviterUser:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onUserConnectionRequestWithInviterUser:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TUIUserInfo","preciseIdentifier":"c:objc(cs)TUIUserInfo","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"inviterUser","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionRequest(inviterUser:)\/title","value":"onUserConnectionRequestWithInviterUser:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onUserConnectionRequestWithInviterUser:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver~1onUserConnectionRequest(inviterUser:)\/fragments"},{"op":"replace","value":"ConnectionObserver","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ConnectionObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ConnectionObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConnectionObserver\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}