{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessageextensionsdeleted(msgid:extensionkeys:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessageextensionsdeleted(msgid:extensionkeys:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageExtensionsDeleted(msgID:extensionKeys:)"},"kind":"symbol","metadata":{"symbolKind":"method","externalID":"c:@CM@AtomicXCore@objc(cs)MessageListStoreImpl(im)onRecvMessageExtensionsDeleted:extensionKeys:","modules":[{"name":"AtomicXCore"}],"roleHeading":"Instance Method","role":"symbol","title":"onRecvMessageExtensionsDeleted(msgID:extensionKeys:)","extendedModule":"AtomicXCore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRecvMessageExtensionsDeleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"msgID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extensionKeys"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"onRecvMessageExtensionsDeleted:extensionKeys:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageExtensionsDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"msgID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"extensionKeys","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"V2TIMAdvancedMsgListener.onRecvMessageExtensionsDeleted(msgID:extensionKeys:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl","title":"MessageListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStoreImpl"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageExtensionsDeleted(msgID:extensionKeys:)":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageExtensionsDeleted(msgID:extensionKeys:)","title":"onRecvMessageExtensionsDeleted(msgID:extensionKeys:)","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessageextensionsdeleted(msgid:extensionkeys:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRecvMessageExtensionsDeleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"msgID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"extensionKeys","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"onRecvMessageExtensionsDeleted:extensionKeys:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onRecvMessageExtensionsDeleted:extensionKeys:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageExtensionsDeleted:extensionKeys:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"onRecvMessageExtensionsDeleted:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"msgID","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"extensionKeys:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"extensionKeys"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/title","value":"MessageListStoreImpl","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/fragments","value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/navigatorTitle","value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageExtensionsDeleted(msgID:extensionKeys:)\/title","value":"onRecvMessageExtensionsDeleted:extensionKeys:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageExtensionsDeleted(msgID:extensionKeys:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onRecvMessageExtensionsDeleted:extensionKeys:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}