{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl"]]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"V2TIMAdvancedMsgListener.onRecvMessageReactionsChanged(changeList:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReactionsChanged(changeList:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagereactionschanged(changelist:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagereactionschanged(changelist:)"]}],"metadata":{"roleHeading":"Instance Method","title":"onRecvMessageReactionsChanged(changeList:)","symbolKind":"method","navigatorTitle":[{"text":"onRecvMessageReactionsChanged:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageReactionsChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"changeList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMMessageReactionChangeInfo","preciseIdentifier":"c:objc(cs)V2TIMMessageReactionChangeInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"modules":[{"name":"AtomicXCore"}],"role":"symbol","extendedModule":"AtomicXCore","externalID":"c:@CM@AtomicXCore@objc(cs)MessageListStoreImpl(im)onRecvMessageReactionsChanged:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageReactionsChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"changeList","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"V2TIMMessageReactionChangeInfo","preciseIdentifier":"c:objc(cs)V2TIMMessageReactionChangeInfo"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageReactionsChanged(changeList:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReactionsChanged(changeList:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageReactionsChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"changeList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMMessageReactionChangeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMMessageReactionChangeInfo"},{"text":"])","kind":"text"}],"title":"onRecvMessageReactionsChanged(changeList:)","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagereactionschanged(changelist:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"onRecvMessageReactionsChanged:","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl","title":"MessageListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStoreImpl"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onRecvMessageReactionsChanged:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageReactionsChanged:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onRecvMessageReactionsChanged:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<V2TIMMessageReactionChangeInfo *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"changeList"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageReactionsChanged(changeList:)\/title","value":"onRecvMessageReactionsChanged:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageReactionsChanged(changeList:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageReactionsChanged:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/title","value":"MessageListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/fragments","value":[{"text":"MessageListStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/navigatorTitle","value":[{"text":"MessageListStoreImpl","kind":"identifier"}]}]}]}