{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"V2TIMAdvancedMsgListener.onRecvNewMessage(msg:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvNewMessage(msg:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvnewmessage(msg:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvnewmessage(msg:)"]}],"metadata":{"roleHeading":"Instance Method","title":"onRecvNewMessage(msg:)","symbolKind":"method","navigatorTitle":[{"text":"onRecvNewMessage:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvNewMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"msg","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)V2TIMMessage","text":"V2TIMMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"AtomicXCore"}],"role":"symbol","extendedModule":"AtomicXCore","externalID":"c:@CM@AtomicXCore@objc(cs)MessageListStoreImpl(im)onRecvNewMessage:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvNewMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"msg","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"V2TIMMessage","preciseIdentifier":"c:objc(cs)V2TIMMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl","title":"MessageListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStoreImpl"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvNewMessage(msg:)":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvNewMessage(msg:)","title":"onRecvNewMessage(msg:)","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvnewmessage(msg:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvNewMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"msg","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"V2TIMMessage","preciseIdentifier":"c:objc(cs)V2TIMMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onRecvNewMessage:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"onRecvNewMessage:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onRecvNewMessage:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onRecvNewMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"V2TIMMessage","preciseIdentifier":"c:objc(cs)V2TIMMessage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"msg","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MessageListStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/title","op":"replace"},{"value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/fragments","op":"replace"},{"value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/navigatorTitle","op":"replace"},{"value":"onRecvNewMessage:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvNewMessage(msg:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onRecvNewMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvNewMessage(msg:)\/fragments","op":"replace"}]}]}