{"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReadReceipts(receiptList:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageReadReceipts","kind":"identifier"},{"text":"(","kind":"text"},{"text":"receiptList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMMessageReceipt","preciseIdentifier":"c:objc(cs)V2TIMMessageReceipt","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagereadreceipts(receiptlist:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagereadreceipts(receiptlist:)"]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"V2TIMAdvancedMsgListener.onRecvMessageReadReceipts(receiptList:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRecvMessageReadReceipts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"receiptList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMMessageReceipt","text":"V2TIMMessageReceipt"},{"kind":"text","text":"])"}],"extendedModule":"AtomicXCore","externalID":"c:@CM@AtomicXCore@objc(cs)MessageListStoreImpl(im)onRecvMessageReadReceipts:","modules":[{"name":"AtomicXCore"}],"title":"onRecvMessageReadReceipts(receiptList:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onRecvMessageReadReceipts:"}]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl","title":"MessageListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStoreImpl"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageReadReceipts(receiptList:)":{"url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagereadreceipts(receiptlist:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRecvMessageReadReceipts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"receiptList"},{"kind":"text","text":": ["},{"text":"V2TIMMessageReceipt","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMMessageReceipt"},{"text":"])","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"onRecvMessageReadReceipts:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReadReceipts(receiptList:)","title":"onRecvMessageReadReceipts(receiptList:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onRecvMessageReadReceipts:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageReadReceipts:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onRecvMessageReadReceipts:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<V2TIMMessageReceipt *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"receiptList","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/title","value":"MessageListStoreImpl","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/fragments","value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/navigatorTitle","value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageReadReceipts(receiptList:)\/title","value":"onRecvMessageReadReceipts:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageReadReceipts(receiptList:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageReadReceipts:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}