{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageRevoked(msgID:operateUser:reason:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"V2TIMAdvancedMsgListener.onRecvMessageRevoked(msgID:operateUser:reason:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageRevoked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"msgID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"operateUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"V2TIMUserFullInfo","preciseIdentifier":"c:objc(cs)V2TIMUserFullInfo","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"title":"onRecvMessageRevoked(msgID:operateUser:reason:)","externalID":"c:@CM@AtomicXCore@objc(cs)MessageListStoreImpl(im)onRecvMessageRevoked:operateUser:reason:","modules":[{"name":"AtomicXCore"}],"extendedModule":"AtomicXCore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRecvMessageRevoked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"msgID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"operateUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMUserFullInfo","text":"V2TIMUserFullInfo"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"onRecvMessageRevoked:operateUser:reason:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagerevoked(msgid:operateuser:reason:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagerevoked(msgid:operateuser:reason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageRevoked(msgID:operateUser:reason:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageRevoked(msgID:operateUser:reason:)","title":"onRecvMessageRevoked(msgID:operateUser:reason:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRecvMessageRevoked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"msgID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"operateUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMUserFullInfo","text":"V2TIMUserFullInfo"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"onRecvMessageRevoked:operateUser:reason:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagerevoked(msgid:operateuser:reason:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl","title":"MessageListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStoreImpl"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onRecvMessageRevoked:operateUser:reason:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageRevoked:operateUser:reason:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onRecvMessageRevoked:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"msgID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"operateUser:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"V2TIMUserFullInfo","preciseIdentifier":"c:objc(cs)V2TIMUserFullInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"operateUser","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reason:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageRevoked(msgID:operateUser:reason:)\/title","value":"onRecvMessageRevoked:operateUser:reason:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageRevoked(msgID:operateUser:reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageRevoked:operateUser:reason:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/title","value":"MessageListStoreImpl","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/fragments","value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/navigatorTitle","value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}