{"metadata":{"modules":[{"name":"AtomicXCore"}],"role":"collectionGroup","roleHeading":"API Collection","title":"V2TIMAdvancedMsgListener Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/v2timadvancedmsglistener-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl\/v2timadvancedmsglistener-implementations"]}],"kind":"article","topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageExtensionsDeleted(msgID:extensionKeys:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageModified(msg:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReactionsChanged(changeList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReadReceipts(receiptList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageRevoked(msgID:operateUser:reason:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvNewMessage(msg:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/V2TIMAdvancedMsgListener-Implementations","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl","title":"MessageListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStoreImpl"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvNewMessage(msg:)":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvNewMessage(msg:)","title":"onRecvNewMessage(msg:)","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvnewmessage(msg:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvNewMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"msg","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"V2TIMMessage","preciseIdentifier":"c:objc(cs)V2TIMMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onRecvNewMessage:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageModified(msg:)":{"kind":"symbol","abstract":[],"type":"topic","title":"onRecvMessageModified(msg:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageModified(msg:)","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagemodified(msg:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageModified","kind":"identifier"},{"text":"(","kind":"text"},{"text":"msg","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)V2TIMMessage","text":"V2TIMMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onRecvMessageModified:"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageReadReceipts(receiptList:)":{"url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagereadreceipts(receiptlist:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRecvMessageReadReceipts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"receiptList"},{"kind":"text","text":": ["},{"text":"V2TIMMessageReceipt","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMMessageReceipt"},{"text":"])","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"onRecvMessageReadReceipts:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReadReceipts(receiptList:)","title":"onRecvMessageReadReceipts(receiptList:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageRevoked(msgID:operateUser:reason:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageRevoked(msgID:operateUser:reason:)","title":"onRecvMessageRevoked(msgID:operateUser:reason:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRecvMessageRevoked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"msgID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"operateUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMUserFullInfo","text":"V2TIMUserFullInfo"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"onRecvMessageRevoked:operateUser:reason:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagerevoked(msgid:operateuser:reason:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageReactionsChanged(changeList:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReactionsChanged(changeList:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRecvMessageReactionsChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"changeList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMMessageReactionChangeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMMessageReactionChangeInfo"},{"text":"])","kind":"text"}],"title":"onRecvMessageReactionsChanged(changeList:)","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessagereactionschanged(changelist:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"onRecvMessageReactionsChanged:","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/onRecvMessageExtensionsDeleted(msgID:extensionKeys:)":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageExtensionsDeleted(msgID:extensionKeys:)","title":"onRecvMessageExtensionsDeleted(msgID:extensionKeys:)","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/onrecvmessageextensionsdeleted(msgid:extensionkeys:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onRecvMessageExtensionsDeleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"msgID"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"extensionKeys","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"onRecvMessageExtensionsDeleted:extensionKeys:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageExtensionsDeleted(msgID:extensionKeys:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageModified(msg:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReactionsChanged(changeList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageReadReceipts(receiptList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvMessageRevoked(msgID:operateUser:reason:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/onRecvNewMessage(msg:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"MessageListStoreImpl","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/title"},{"value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/fragments"},{"value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/navigatorTitle"},{"value":"onRecvNewMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvNewMessage(msg:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onRecvNewMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvNewMessage(msg:)\/fragments"},{"value":"onRecvMessageModified:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageModified(msg:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageModified:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageModified(msg:)\/fragments"},{"value":"onRecvMessageReadReceipts:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageReadReceipts(receiptList:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageReadReceipts:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageReadReceipts(receiptList:)\/fragments"},{"value":"onRecvMessageRevoked:operateUser:reason:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageRevoked(msgID:operateUser:reason:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageRevoked:operateUser:reason:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageRevoked(msgID:operateUser:reason:)\/fragments"},{"value":"onRecvMessageReactionsChanged:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageReactionsChanged(changeList:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageReactionsChanged:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageReactionsChanged(changeList:)\/fragments"},{"value":"onRecvMessageExtensionsDeleted:extensionKeys:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageExtensionsDeleted(msgID:extensionKeys:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onRecvMessageExtensionsDeleted:extensionKeys:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl~1onRecvMessageExtensionsDeleted(msgID:extensionKeys:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}