{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/registerBattleObserver(observer:)"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerBattleObserver","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"observer"},{"kind":"text","text":": "},{"text":"BattleObserver","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","preciseIdentifier":"c:@M@AtomicXCore@objc(pl)BattleObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"platforms":[{"deprecated":true,"beta":false,"unavailable":false}],"title":"registerBattleObserver(observer:)","externalID":"s:11AtomicXCore12LiveCoreViewC22registerBattleObserver8observeryAA0gH0_p_tF","modules":[{"name":"AtomicXCore"}],"extendedModule":"AtomicXCore","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerBattleObserver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(pl)BattleObserver","text":"BattleObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"paths":["\/documentation\/atomicxcore\/livecoreview\/registerbattleobserver(observer:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/registerBattleObserver(observer:)":{"url":"\/documentation\/atomicxcore\/livecoreview\/registerbattleobserver(observer:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerBattleObserver"},{"kind":"text","text":"("},{"text":"observer","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(pl)BattleObserver","text":"BattleObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","deprecated":true,"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/registerBattleObserver(observer:)","type":"topic","title":"registerBattleObserver(observer:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","title":"LiveCoreView","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveCoreView","kind":"identifier"}],"navigatorTitle":[{"text":"LiveCoreView","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/BattleObserver":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/BattleObserver","title":"BattleObserver","deprecated":true,"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BattleObserver","kind":"identifier"}],"navigatorTitle":[{"text":"BattleObserver","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/battleobserver","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"LiveCoreView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title"},{"value":[{"text":"LiveCoreView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments"},{"value":[{"text":"LiveCoreView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle"},{"value":"BattleObserver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/title"},{"value":[{"text":"BattleObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/fragments"},{"value":[{"text":"BattleObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1BattleObserver\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}