{"metadata":{"symbolKind":"method","externalID":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF","modules":[{"name":"AtomicXCore"}],"roleHeading":"Instance Method","title":"subscribeState(_:)","role":"symbol","extendedModule":"AtomicXCore","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscribeState","kind":"identifier"},{"text":"<","kind":"text"},{"text":"State","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Value","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"StatePublisherSelector","preciseIdentifier":"s:11AtomicXCore22StatePublisherSelectorC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"State","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF0G0L_xmfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Value","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF5ValueL_q_mfp","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Value","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF5ValueL_q_mfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Never","preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":true}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/livecoreview\/subscribestate(_:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscribeState","kind":"identifier"},{"text":"<","kind":"text"},{"text":"State","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Value","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"selector","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"StatePublisherSelector","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisherSelector","preciseIdentifier":"s:11AtomicXCore22StatePublisherSelectorC"},{"text":"<","kind":"text"},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF0G0L_xmfp"},{"text":", ","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF5ValueL_q_mfp"},{"text":">) -> ","kind":"text"},{"text":"AnyPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine12AnyPublisherV"},{"text":"<","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF5ValueL_q_mfp"},{"text":", ","kind":"text"},{"text":"Never","kind":"typeIdentifier","preciseIdentifier":"s:s5NeverO"},{"text":">","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/subscribeState(_:)"},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView/subscribeState(_:)":{"url":"\/documentation\/atomicxcore\/livecoreview\/subscribestate(_:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView\/subscribeState(_:)","kind":"symbol","deprecated":true,"title":"subscribeState(_:)","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subscribeState","kind":"identifier"},{"text":"<","kind":"text"},{"text":"State","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Value","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"StatePublisherSelector","preciseIdentifier":"s:11AtomicXCore22StatePublisherSelectorC","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"State","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF0G0L_xmfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Value","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF5ValueL_q_mfp","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"AnyPublisher","preciseIdentifier":"s:7Combine12AnyPublisherV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Value","preciseIdentifier":"s:11AtomicXCore12LiveCoreViewC14subscribeStatey7Combine12AnyPublisherVyq_s5NeverOGAA0gJ8SelectorCyxq_Gr0_lF5ValueL_q_mfp","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Never","preciseIdentifier":"s:s5NeverO","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/LiveCoreView":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/LiveCoreView","title":"LiveCoreView","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LiveCoreView","kind":"identifier"}],"navigatorTitle":[{"text":"LiveCoreView","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/livecoreview"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/StatePublisherSelector":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisherSelector","title":"StatePublisherSelector","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatePublisherSelector"}],"navigatorTitle":[{"kind":"identifier","text":"StatePublisherSelector"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/statepublisherselector"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/title","value":"LiveCoreView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/fragments","value":[{"text":"LiveCoreView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1LiveCoreView\/navigatorTitle","value":[{"text":"LiveCoreView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}