{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/init(participantId:streamType:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/atomicxcore\/participantview\/init(participantid:streamtype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"init(participantId:streamType:)","externalID":"s:11AtomicXCore15ParticipantViewC13participantId10streamTypeACSS_So014TUIVideoStreamH0Vtcfc","modules":[{"name":"AtomicXCore"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"participantId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"streamType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@TUIVideoStreamType","text":"TUIVideoStreamType"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"participantId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"streamType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@TUIVideoStreamType","text":"TUIVideoStreamType"},{"kind":"text","text":")"}]}]}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView","title":"ParticipantView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ParticipantView"}],"navigatorTitle":[{"kind":"identifier","text":"ParticipantView"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/participantview"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ParticipantView/init(participantId:streamType:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ParticipantView\/init(participantId:streamType:)","title":"init(participantId:streamType:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"participantId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"streamType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TUIVideoStreamType","preciseIdentifier":"c:@E@TUIVideoStreamType"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/participantview\/init(participantid:streamtype:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ParticipantView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/title"},{"value":[{"kind":"identifier","text":"ParticipantView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ParticipantView"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ParticipantView\/navigatorTitle"}]}]}