{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStoreImpl","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMConversationListener","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMFriendshipListener","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMGroupListener","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s8CopyableP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/clearConversationMessages(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/clearConversationUnreadCount(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/deleteConversation(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/fetchConversationInfo(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/fetchConversationList(_:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/fetchMoreConversationList(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/getConversationTotalUnreadCount(completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/markConversationUnread(_:unread:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/muteConversation(_:mute:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/pinConversation(_:pin:completion:)"],"title":"Instance Methods"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMConversationListener-Implementations","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMFriendshipListener-Implementations","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMGroupListener-Implementations"],"title":"Default Implementations"}],"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationListStoreImpl","kind":"identifier"}],"externalID":"c:@M@AtomicXCore@objc(cs)ConversationListStoreImpl","modules":[{"name":"AtomicXCore"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","title":"ConversationListStoreImpl","navigatorTitle":[{"text":"ConversationListStoreImpl","kind":"identifier"}]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/fetchMoreConversationList(completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/fetchMoreConversationList(completion:)","title":"fetchMoreConversationList(completion:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchMoreConversationList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/fetchmoreconversationlist(completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl","title":"ConversationListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/clearConversationMessages(_:completion:)":{"kind":"symbol","abstract":[],"type":"topic","title":"clearConversationMessages(_:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/clearConversationMessages(_:completion:)","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/clearconversationmessages(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearConversationMessages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/pinConversation(_:pin:completion:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/pinConversation(_:pin:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"pin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/pinconversation(_:pin:completion:)","title":"pinConversation(_:pin:completion:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/muteConversation(_:mute:completion:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/muteConversation(_:mute:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"muteConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"mute","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/muteconversation(_:mute:completion:)","title":"muteConversation(_:mute:completion:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/fetchConversationInfo(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/fetchConversationInfo(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchConversationInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/fetchconversationinfo(_:completion:)","title":"fetchConversationInfo(_:completion:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/V2TIMGroupListener-Implementations":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMGroupListener-Implementations","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/v2timgrouplistener-implementations","title":"V2TIMGroupListener Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://org.cocoapods.AtomicXCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/fetchConversationList(_:completion:)":{"url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/fetchconversationlist(_:completion:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/fetchConversationList(_:completion:)","kind":"symbol","type":"topic","title":"fetchConversationList(_:completion:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fetchConversationList","kind":"identifier"},{"kind":"text","text":"("},{"text":"ConversationFetchOption","preciseIdentifier":"s:11AtomicXCore23ConversationFetchOptionV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore","title":"ConversationListStore","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStore","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationListStore","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststore","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/objc(pl)V2TIMGroupListener":{"title":"V2TIMGroupListener","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMGroupListener","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/objc(pl)V2TIMConversationListener":{"title":"V2TIMConversationListener","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMConversationListener","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/getConversationTotalUnreadCount(completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/getConversationTotalUnreadCount(completion:)","title":"getConversationTotalUnreadCount(completion:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getConversationTotalUnreadCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/getconversationtotalunreadcount(completion:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/deleteConversation(_:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/deleteConversation(_:completion:)","title":"deleteConversation(_:completion:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteConversation","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","text":"CompletionClosure","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/deleteconversation(_:completion:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/clearConversationUnreadCount(_:completion:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/clearConversationUnreadCount(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearConversationUnreadCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"title":"clearConversationUnreadCount(_:completion:)","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/clearconversationunreadcount(_:completion:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/V2TIMFriendshipListener-Implementations":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMFriendshipListener-Implementations","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/v2timfriendshiplistener-implementations","title":"V2TIMFriendshipListener Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/markConversationUnread(_:unread:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/markConversationUnread(_:unread:completion:)","title":"markConversationUnread(_:unread:completion:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"markConversationUnread","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"unread","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/markconversationunread(_:unread:completion:)"},"doc://org.cocoapods.AtomicXCore/objc(pl)V2TIMFriendshipListener":{"title":"V2TIMFriendshipListener","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMFriendshipListener","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/V2TIMConversationListener-Implementations":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMConversationListener-Implementations","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/v2timconversationlistener-implementations","title":"V2TIMConversationListener Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://org.cocoapods.AtomicXCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ConversationListStoreImpl"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConversationListStoreImpl"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationListStoreImpl"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMConversationListener-Implementations","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMFriendshipListener-Implementations","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMGroupListener-Implementations"],"generated":true,"title":"Default Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMConversationListener","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMFriendshipListener","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMGroupListener"],"type":"conformsTo","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStoreImpl","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)ConversationListStore","text":"ConversationListStore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStore","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/title","value":"ConversationListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/fragments","value":[{"kind":"identifier","text":"ConversationListStoreImpl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationListStoreImpl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/title","value":"ConversationListStore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/fragments","value":[{"kind":"identifier","text":"ConversationListStore"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStore\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationListStore"}]}]}]}