{"variants":[{"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/fetchgroupinfo(groupid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/fetchGroupInfo(groupID:completion:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl"]]},"metadata":{"symbolKind":"method","externalID":"s:11AtomicXCore20ContactListStoreImplC14fetchGroupInfo7groupID10completionySS_ys6ResultOyytAA05ErrorI0VGcSgtF","modules":[{"name":"AtomicXCore"}],"roleHeading":"Instance Method","role":"symbol","title":"fetchGroupInfo(groupID:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchGroupInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchGroupInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/fetchGroupInfo(groupID:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/fetchGroupInfo(groupID:completion:)","title":"fetchGroupInfo(groupID:completion:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchGroupInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/fetchgroupinfo(groupid:completion:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl","title":"ContactListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CompletionClosure":{"abstract":[],"url":"\/documentation\/atomicxcore\/completionclosure","kind":"symbol","title":"CompletionClosure","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionClosure","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"CompletionClosure","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CompletionClosure"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/title","value":"ContactListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/fragments","value":[{"text":"ContactListStoreImpl","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/navigatorTitle","value":[{"text":"ContactListStoreImpl","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}