{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListAdded(applicationList:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"V2TIMFriendshipListener.onFriendApplicationListAdded(applicationList:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFriendApplicationListAdded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applicationList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"V2TIMFriendApplication","preciseIdentifier":"c:objc(cs)V2TIMFriendApplication"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"onFriendApplicationListAdded(applicationList:)","externalID":"c:@CM@AtomicXCore@objc(cs)ContactListStoreImpl(im)onFriendApplicationListAdded:","modules":[{"name":"AtomicXCore"}],"extendedModule":"AtomicXCore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFriendApplicationListAdded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applicationList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"V2TIMFriendApplication","preciseIdentifier":"c:objc(cs)V2TIMFriendApplication"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"onFriendApplicationListAdded:"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendapplicationlistadded(applicationlist:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendapplicationlistadded(applicationlist:)"]}],"kind":"symbol","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onFriendApplicationListAdded(applicationList:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListAdded(applicationList:)","title":"onFriendApplicationListAdded(applicationList:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFriendApplicationListAdded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applicationList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"V2TIMFriendApplication","preciseIdentifier":"c:objc(cs)V2TIMFriendApplication"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"onFriendApplicationListAdded:"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendapplicationlistadded(applicationlist:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl","title":"ContactListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onFriendApplicationListAdded:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onFriendApplicationListAdded:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onFriendApplicationListAdded:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<V2TIMFriendApplication *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"applicationList"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListAdded(applicationList:)\/title","value":"onFriendApplicationListAdded:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListAdded(applicationList:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onFriendApplicationListAdded:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/title","value":"ContactListStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/fragments","value":[{"kind":"identifier","text":"ContactListStoreImpl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/navigatorTitle","value":[{"kind":"identifier","text":"ContactListStoreImpl"}]}]}]}