{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onFriendListAdded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"infoList","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMFriendInfo","text":"V2TIMFriendInfo"},{"kind":"text","text":"])"}],"extendedModule":"AtomicXCore","externalID":"c:@CM@AtomicXCore@objc(cs)ContactListStoreImpl(im)onFriendListAdded:","modules":[{"name":"AtomicXCore"}],"title":"onFriendListAdded(infoList:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"onFriendListAdded:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendlistadded(infolist:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendlistadded(infolist:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onFriendListAdded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"infoList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMFriendInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMFriendInfo"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"V2TIMFriendshipListener.onFriendListAdded(infoList:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListAdded(infoList:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onFriendListAdded(infoList:)":{"kind":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendlistadded(infolist:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onFriendListAdded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"infoList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMFriendInfo","preciseIdentifier":"c:objc(cs)V2TIMFriendInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"onFriendListAdded:","kind":"identifier"}],"title":"onFriendListAdded(infoList:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListAdded(infoList:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl","title":"ContactListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onFriendListAdded:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onFriendListAdded:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onFriendListAdded:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<V2TIMFriendInfo *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"infoList"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"onFriendListAdded:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendListAdded(infoList:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onFriendListAdded:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendListAdded(infoList:)\/fragments"},{"op":"replace","value":"ContactListStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/title"},{"op":"replace","value":[{"text":"ContactListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/fragments"},{"op":"replace","value":[{"text":"ContactListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}