{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/V2TIMFriendshipListener-Implementations"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onBlackListAdded(infoList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onBlackListDeleted(userIDList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListAdded(applicationList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListDeleted(userIDList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListRead()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListAdded(infoList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListDeleted(userIDList:)"],"generated":true,"anchor":"Instance-Methods"}],"metadata":{"title":"V2TIMFriendshipListener Implementations","role":"collectionGroup","modules":[{"name":"AtomicXCore"}],"roleHeading":"API Collection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/v2timfriendshiplistener-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/contactliststoreimpl\/v2timfriendshiplistener-implementations"]}],"kind":"article","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onFriendListDeleted(userIDList:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListDeleted(userIDList:)","title":"onFriendListDeleted(userIDList:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onFriendListDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIDList","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"text":"]!)","kind":"text"}],"navigatorTitle":[{"text":"onFriendListDeleted:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendlistdeleted(useridlist:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onBlackListDeleted(userIDList:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onBlackListDeleted(userIDList:)","title":"onBlackListDeleted(userIDList:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onBlackListDeleted","kind":"identifier"},{"kind":"text","text":"("},{"text":"userIDList","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]!)"}],"navigatorTitle":[{"kind":"identifier","text":"onBlackListDeleted:"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onblacklistdeleted(useridlist:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onFriendApplicationListDeleted(userIDList:)":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListDeleted(userIDList:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFriendApplicationListDeleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIDList"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"title":"onFriendApplicationListDeleted(userIDList:)","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendapplicationlistdeleted(useridlist:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onFriendApplicationListDeleted:"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onFriendApplicationListRead()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListRead()","title":"onFriendApplicationListRead()","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFriendApplicationListRead"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"onFriendApplicationListRead"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendapplicationlistread()"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onBlackListAdded(infoList:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onBlackListAdded(infoList:)","title":"onBlackListAdded(infoList:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onBlackListAdded","kind":"identifier"},{"kind":"text","text":"("},{"text":"infoList","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)V2TIMFriendInfo","text":"V2TIMFriendInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"onBlackListAdded:","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onblacklistadded(infolist:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl","title":"ContactListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ContactListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onFriendApplicationListAdded(applicationList:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListAdded(applicationList:)","title":"onFriendApplicationListAdded(applicationList:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onFriendApplicationListAdded"},{"kind":"text","text":"("},{"kind":"externalParam","text":"applicationList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"V2TIMFriendApplication","preciseIdentifier":"c:objc(cs)V2TIMFriendApplication"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"onFriendApplicationListAdded:"}],"role":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendapplicationlistadded(applicationlist:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ContactListStoreImpl/onFriendListAdded(infoList:)":{"kind":"symbol","url":"\/documentation\/atomicxcore\/contactliststoreimpl\/onfriendlistadded(infolist:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onFriendListAdded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"infoList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMFriendInfo","preciseIdentifier":"c:objc(cs)V2TIMFriendInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"onFriendListAdded:","kind":"identifier"}],"title":"onFriendListAdded(infoList:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListAdded(infoList:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onBlackListAdded(infoList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onBlackListDeleted(userIDList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListAdded(applicationList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListDeleted(userIDList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendApplicationListRead()","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListAdded(infoList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ContactListStoreImpl\/onFriendListDeleted(userIDList:)"],"title":"Instance Methods"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":"onFriendListDeleted:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendListDeleted(userIDList:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onFriendListDeleted:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendListDeleted(userIDList:)\/fragments","op":"replace"},{"op":"replace","value":"onBlackListDeleted:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onBlackListDeleted(userIDList:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onBlackListDeleted:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onBlackListDeleted(userIDList:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListDeleted(userIDList:)\/title","value":"onFriendApplicationListDeleted:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onFriendApplicationListDeleted:"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListDeleted(userIDList:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListRead()\/title","value":"onFriendApplicationListRead","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onFriendApplicationListRead","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListRead()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onBlackListAdded(infoList:)\/title","op":"replace","value":"onBlackListAdded:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onBlackListAdded:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onBlackListAdded(infoList:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/title","value":"ContactListStoreImpl","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/fragments","value":[{"text":"ContactListStoreImpl","kind":"identifier"}]},{"value":[{"text":"ContactListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListAdded(applicationList:)\/title","value":"onFriendApplicationListAdded:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendApplicationListAdded(applicationList:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onFriendApplicationListAdded:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendListAdded(infoList:)\/title","op":"replace","value":"onFriendListAdded:"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ContactListStoreImpl~1onFriendListAdded(infoList:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onFriendListAdded:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}