{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callparticipantstore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/callparticipantstore"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore"},"kind":"symbol","metadata":{"symbolKind":"class","externalID":"c:@M@AtomicXCore@objc(cs)CallParticipantStore","modules":[{"name":"AtomicXCore"}],"roleHeading":"Class","role":"symbol","title":"CallParticipantStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallParticipantStore"}],"navigatorTitle":[{"text":"CallParticipantStore","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallParticipantStore"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/state"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/shared"],"title":"Type Properties","anchor":"Type-Properties"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl"],"title":"Inherited By"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH"],"title":"Conforms To"}],"references":{"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.AtomicXCore/SH":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStore/shared":{"url":"\/documentation\/atomicxcore\/callparticipantstore\/shared","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/shared","kind":"symbol","type":"topic","title":"shared","role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"typeIdentifier","preciseIdentifier":"c:@M@AtomicXCore@objc(cs)CallParticipantStoreImpl"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStore/init":{"url":"\/documentation\/atomicxcore\/callparticipantstore\/init","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/init","kind":"symbol","type":"topic","title":"init","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl","title":"CallParticipantStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"CallParticipantStoreImpl","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstoreimpl"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.AtomicXCore/SQ":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.AtomicXCore/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStore/state":{"url":"\/documentation\/atomicxcore\/callparticipantstore\/state","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/state","kind":"symbol","type":"topic","title":"state","role":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatePublisher","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore14StatePublisherC"},{"text":"<","kind":"text"},{"text":"CallParticipantState","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore20CallParticipantStateV"},{"text":">","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStore":{"abstract":[],"url":"\/documentation\/atomicxcore\/callparticipantstore","kind":"symbol","title":"CallParticipantStore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStore","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"CallParticipantStore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CallParticipantStore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallParticipantStore"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallParticipantStore"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/init"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStoreImpl"],"type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStore","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/title","value":"CallParticipantStoreImpl"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/fragments","value":[{"kind":"identifier","text":"CallParticipantStoreImpl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStoreImpl\/navigatorTitle","value":[{"kind":"identifier","text":"CallParticipantStoreImpl"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/title","value":"CallParticipantStore"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/fragments","value":[{"kind":"identifier","text":"CallParticipantStore"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/navigatorTitle","value":[{"kind":"identifier","text":"CallParticipantStore"}]}]}]}