{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/messageliststoreimpl"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl"},"kind":"symbol","metadata":{"symbolKind":"class","externalID":"c:@M@AtomicXCore@objc(cs)MessageListStoreImpl","modules":[{"name":"AtomicXCore"}],"roleHeading":"Class","title":"MessageListStoreImpl","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListStoreImpl"}],"navigatorTitle":[{"text":"MessageListStoreImpl","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListStoreImpl"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/downloadMessageResource(_:resourceType:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/fetchMessageList(with:completion:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/fetchMoreMessageList(direction:completion:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/V2TIMAdvancedMsgListener-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMAdvancedMsgListener","doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","doc:\/\/org.cocoapods.AtomicXCore\/s8CopyableP","doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.AtomicXCore\/SQ","doc:\/\/org.cocoapods.AtomicXCore\/SH"],"type":"conformsTo"}],"references":{"doc://org.cocoapods.AtomicXCore/SQ":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore","title":"MessageListStore","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStore","kind":"identifier"}],"navigatorTitle":[{"text":"MessageListStore","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststore"},"doc://org.cocoapods.AtomicXCore/objc(pl)V2TIMAdvancedMsgListener":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMAdvancedMsgListener","title":"V2TIMAdvancedMsgListener","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/fetchMessageList(with:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/fetchMessageList(with:completion:)","title":"fetchMessageList(with:completion:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchMessageList"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageFetchOption","preciseIdentifier":"s:11AtomicXCore18MessageFetchOptionV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"kind":"text","text":"?)"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/fetchmessagelist(with:completion:)"},"doc://org.cocoapods.AtomicXCore/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/downloadMessageResource(_:resourceType:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/downloadMessageResource(_:resourceType:completion:)","title":"downloadMessageResource(_:resourceType:completion:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"downloadMessageResource","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11AtomicXCore11MessageInfoV","kind":"typeIdentifier","text":"MessageInfo"},{"text":", ","kind":"text"},{"text":"resourceType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageMediaFileType","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore20MessageMediaFileTypeO"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea"},{"text":"?)","kind":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/downloadmessageresource(_:resourcetype:completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/fetchMoreMessageList(direction:completion:)":{"kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/fetchmoremessagelist(direction:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchMoreMessageList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"direction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageFetchDirection","preciseIdentifier":"s:11AtomicXCore21MessageFetchDirectionV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CompletionClosure","preciseIdentifier":"s:11AtomicXCore17CompletionClosurea","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[],"role":"symbol","title":"fetchMoreMessageList(direction:completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/fetchMoreMessageList(direction:completion:)"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl/V2TIMAdvancedMsgListener-Implementations":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/V2TIMAdvancedMsgListener-Implementations","title":"V2TIMAdvancedMsgListener Implementations","url":"\/documentation\/atomicxcore\/messageliststoreimpl\/v2timadvancedmsglistener-implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://org.cocoapods.AtomicXCore/SH":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/MessageListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl","title":"MessageListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListStoreImpl"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/messageliststoreimpl"},"doc://org.cocoapods.AtomicXCore/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MessageListStoreImpl","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStoreImpl\/V2TIMAdvancedMsgListener-Implementations"],"title":"Default Implementations"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/objc(pl)V2TIMAdvancedMsgListener"],"title":"Conforms To"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListStoreImpl","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@AtomicXCore@objc(cs)MessageListStore","text":"MessageListStore","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/MessageListStore","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MessageListStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/title","op":"replace"},{"value":[{"text":"MessageListStore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/fragments"},{"value":[{"text":"MessageListStore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStore\/navigatorTitle"},{"op":"replace","value":"MessageListStoreImpl","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/title"},{"value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/fragments","op":"replace"},{"value":[{"text":"MessageListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1MessageListStoreImpl\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}