{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/state","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/callparticipantstore\/state"]}],"metadata":{"roleHeading":"Instance Property","title":"state","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore14StatePublisherC","text":"StatePublisher"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore20CallParticipantStateV","text":"CallParticipantState"},{"kind":"text","text":">"}],"modules":[{"name":"AtomicXCore"}],"role":"symbol","externalID":"s:11AtomicXCore20CallParticipantStoreC5stateAA14StatePublisherCyAA0cdG0VGvp"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatePublisher","preciseIdentifier":"s:11AtomicXCore14StatePublisherC","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisher"},{"text":"<","kind":"text"},{"text":"CallParticipantState","preciseIdentifier":"s:11AtomicXCore20CallParticipantStateV","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantState"},{"text":">","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/StatePublisher":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/StatePublisher","title":"StatePublisher","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatePublisher","kind":"identifier"}],"navigatorTitle":[{"text":"StatePublisher","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/statepublisher"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantState":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantState","title":"CallParticipantState","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallParticipantState"}],"navigatorTitle":[{"kind":"identifier","text":"CallParticipantState"}],"role":"symbol","kind":"symbol","url":"\/documentation\/atomicxcore\/callparticipantstate"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStore/state":{"url":"\/documentation\/atomicxcore\/callparticipantstore\/state","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore\/state","kind":"symbol","type":"topic","title":"state","role":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatePublisher","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore14StatePublisherC"},{"text":"<","kind":"text"},{"text":"CallParticipantState","kind":"typeIdentifier","preciseIdentifier":"s:11AtomicXCore20CallParticipantStateV"},{"text":">","kind":"text"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/CallParticipantStore":{"abstract":[],"url":"\/documentation\/atomicxcore\/callparticipantstore","kind":"symbol","title":"CallParticipantStore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallParticipantStore","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"CallParticipantStore","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/CallParticipantStore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"CallParticipantStore","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CallParticipantStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CallParticipantStore"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1CallParticipantStore\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}