{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/foreground"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"foreground","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/viewlayer\/foreground"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/viewlayer\/foreground"]}],"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"foreground","kind":"identifier"}],"externalID":"c:@M@AtomicXCore@E@ViewLayer@ViewLayerForeground","modules":[{"name":"AtomicXCore"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","title":"ViewLayer.foreground","navigatorTitle":[{"text":"ViewLayerForeground","kind":"identifier"}]},"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer/foreground":{"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer\/foreground","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"foreground","kind":"identifier"}],"title":"ViewLayer.foreground","type":"topic","url":"\/documentation\/atomicxcore\/viewlayer\/foreground","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"ViewLayerForeground","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ViewLayer":{"abstract":[],"url":"\/documentation\/atomicxcore\/viewlayer","kind":"symbol","title":"ViewLayer","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewLayer"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ViewLayer"}],"identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ViewLayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ViewLayerForeground"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ViewLayerForeground","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ViewLayerForeground","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer~1foreground\/title","value":"ViewLayerForeground"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer~1foreground\/fragments","value":[{"text":"ViewLayerForeground","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/title","value":"ViewLayer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/fragments","value":[{"text":"ViewLayer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ViewLayer\/navigatorTitle","value":[{"text":"ViewLayer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}