{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/onconversationdeleted(conversationidlist:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/onconversationdeleted(conversationidlist:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationDeleted(conversationIDList:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl"]]},"metadata":{"symbolKind":"method","externalID":"c:@CM@AtomicXCore@objc(cs)ConversationListStoreImpl(im)onConversationDeleted:","modules":[{"name":"AtomicXCore"}],"roleHeading":"Instance Method","role":"symbol","title":"onConversationDeleted(conversationIDList:)","extendedModule":"AtomicXCore","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationDeleted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationIDList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"onConversationDeleted:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConversationDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationIDList","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"V2TIMConversationListener.onConversationDeleted(conversationIDList:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl","title":"ConversationListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onConversationDeleted(conversationIDList:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationDeleted(conversationIDList:)","title":"onConversationDeleted(conversationIDList:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConversationDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationIDList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"onConversationDeleted:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/onconversationdeleted(conversationidlist:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onConversationDeleted:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConversationDeleted:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onConversationDeleted:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"conversationIDList","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/title","value":"ConversationListStoreImpl","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/fragments","value":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/navigatorTitle","value":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onConversationDeleted(conversationIDList:)\/title","value":"onConversationDeleted:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onConversationDeleted(conversationIDList:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConversationDeleted:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}