{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl"]]},"identifier":{"url":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/V2TIMConversationListener-Implementations","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationChanged(conversationList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationDeleted(conversationIDList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onNewConversation(conversationList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onTotalUnreadMessageCountChanged(totalUnreadCount:)"],"title":"Instance Methods"}],"metadata":{"modules":[{"name":"AtomicXCore"}],"role":"collectionGroup","roleHeading":"API Collection","title":"V2TIMConversationListener Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/v2timconversationlistener-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/atomicxcore\/conversationliststoreimpl\/v2timconversationlistener-implementations"]}],"kind":"article","references":{"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onTotalUnreadMessageCountChanged(totalUnreadCount:)":{"url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/ontotalunreadmessagecountchanged(totalunreadcount:)","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onTotalUnreadMessageCountChanged(totalUnreadCount:)","kind":"symbol","type":"topic","title":"onTotalUnreadMessageCountChanged(totalUnreadCount:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onTotalUnreadMessageCountChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"totalUnreadCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt64","preciseIdentifier":"s:s6UInt64V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onTotalUnreadMessageCountChanged:","kind":"identifier"}]},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onConversationDeleted(conversationIDList:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationDeleted(conversationIDList:)","title":"onConversationDeleted(conversationIDList:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConversationDeleted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationIDList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"onConversationDeleted:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/onconversationdeleted(conversationidlist:)","kind":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore","title":"AtomicXCore","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/atomicxcore"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onConversationChanged(conversationList:)":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationChanged(conversationList:)","title":"onConversationChanged(conversationList:)","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/onconversationchanged(conversationlist:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)V2TIMConversation","text":"V2TIMConversation"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"onConversationChanged:"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl/onNewConversation(conversationList:)":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onNewConversation(conversationList:)","title":"onNewConversation(conversationList:)","url":"\/documentation\/atomicxcore\/conversationliststoreimpl\/onnewconversation(conversationlist:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onNewConversation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationList","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"V2TIMConversation","preciseIdentifier":"c:objc(cs)V2TIMConversation","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"onNewConversation:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.AtomicXCore/documentation/AtomicXCore/ConversationListStoreImpl":{"type":"topic","identifier":"doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl","title":"ConversationListStoreImpl","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListStoreImpl","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"role":"symbol","url":"\/documentation\/atomicxcore\/conversationliststoreimpl","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationChanged(conversationList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onConversationDeleted(conversationIDList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onNewConversation(conversationList:)","doc:\/\/org.cocoapods.AtomicXCore\/documentation\/AtomicXCore\/ConversationListStoreImpl\/onTotalUnreadMessageCountChanged(totalUnreadCount:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":"onTotalUnreadMessageCountChanged:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onTotalUnreadMessageCountChanged(totalUnreadCount:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onTotalUnreadMessageCountChanged:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onTotalUnreadMessageCountChanged(totalUnreadCount:)\/fragments","op":"replace"},{"value":"onConversationDeleted:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onConversationDeleted(conversationIDList:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onConversationDeleted:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onConversationDeleted(conversationIDList:)\/fragments","op":"replace"},{"op":"replace","value":"onConversationChanged:","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onConversationChanged(conversationList:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onConversationChanged:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onConversationChanged(conversationList:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onNewConversation(conversationList:)\/title","value":"onNewConversation:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onNewConversation:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl~1onNewConversation(conversationList:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/title","value":"ConversationListStoreImpl"},{"op":"replace","value":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/fragments"},{"op":"replace","value":[{"text":"ConversationListStoreImpl","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.AtomicXCore~1documentation~1AtomicXCore~1ConversationListStoreImpl\/navigatorTitle"}]}]}